<a href="https://colab.research.google.com/github/abhishek649/spam-and-ham-mail-detection/blob/main/Spam_and_ham_msg_detection_by_naive_bayes_Algorithm_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
from google.colab import files

uploaded = files.upload()

Saving spam.csv to spam (1).csv


In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [92]:
df=pd.read_csv('spam.csv',encoding='latin-1')

In [93]:
df

v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

In [94]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)

In [95]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [96]:
from sklearn.preprocessing import LabelEncoder

In [97]:
le=LabelEncoder()

In [98]:
y1=le.fit_transform(df['v1'])

In [99]:
df['v3']=y1

In [100]:
df

v1                                                 v2  v3
0      ham  Go until jurong point, crazy.. Available only ...   0
1      ham                      Ok lar... Joking wif u oni...   0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...   1
3      ham  U dun say so early hor... U c already then say...   0
4      ham  Nah I don't think he goes to usf, he lives aro...   0
...    ...                                                ...  ..
5567  spam  This is the 2nd time we have tried 2 contact u...   1
5568   ham              Will Ì_ b going to esplanade fr home?   0
5569   ham  Pity, * was in mood for that. So...any other s...   0
5570   ham  The guy did some bitching but I acted like i'd...   0
5571   ham                         Rofl. Its true to its name   0

[5572 rows x 3 columns]

In [101]:
df.drop(['v1'],axis=1,inplace=True)

In [102]:
df.head()

v2  v3
0  Go until jurong point, crazy.. Available only ...   0
1                      Ok lar... Joking wif u oni...   0
2  Free entry in 2 a wkly comp to win FA Cup fina...   1
3  U dun say so early hor... U c already then say...   0
4  Nah I don't think he goes to usf, he lives aro...   0

In [103]:
x=df['v2']

In [104]:
y=df['v3']

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [107]:
xtrain

1642                             Sleeping nt feeling well
2899    Come aftr  &lt;DECIMAL&gt; ..now i m cleaning ...
480                          Almost there, see u in a sec
3485                     Yeah, probably earlier than that
157     Hello, my love. What are you doing? Did you ge...
                              ...                        
905     Hey what's up charles sorry about the late reply.
5192    Oh oh... Den muz change plan liao... Go back h...
3980    Huh i cant thk of more oredi how many pages do...
235     I have printed it oh. So  &lt;#&gt;  come upst...
5157                              K k:) sms chat with me.
Name: v2, Length: 4457, dtype: object

In [108]:
xtest

1078                             Convey my regards to him
4028             [‰Û_] anyway, many good evenings to u! s
958     My sort code is  and acc no is . The bank is n...
4642                          Sorry i din lock my keypad.
4674    Hi babe its Chloe, how r u? I was smashed on s...
                              ...                        
324                        No problem. How are you doing?
1163    New Theory: Argument wins d SITUATION, but los...
86      For real when u getting on yo? I only need 2 m...
4214                           No dear i was sleeping :-P
90      Yeah do! Don‰Û÷t stand to close tho- you‰Û÷ll ...
Name: v2, Length: 1115, dtype: object

In [115]:
from sklearn.feature_extraction.text import CountVectorizer

In [118]:
fit_text=CountVectorizer()
fit_text.fit(xtrain)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [119]:
x_train=fit_text.transform(xtrain)

In [120]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [121]:
x_test=fit_text.transform(xtest)

In [122]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [123]:
from sklearn.naive_bayes import MultinomialNB

In [124]:
model=MultinomialNB()

In [125]:
model.fit(x_train,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [126]:
model.score(x_test,ytest)

0.9847533632286996

In [127]:
emails=['Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed å£1000 cash or å£5000 prize!','Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']

In [128]:
test_check=fit_text.transform(emails)

In [129]:
model.predict(test_check)

array([1, 0])